modLoader = "javafml"
loaderVersion = "[36,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "fluidium"
version = "${version}"
displayName = "Fluidium"
authors = "Kall"
description = '''
Reduce fluid ticks.
'''
#logoFile = ""

[[dependencies.fluidium]]
modId="duplicationless"
mandatory=true
versionRange="[1.1.5,)"
ordering="NONE"
side="BOTH"