modLoader = "javafml"
loaderVersion = "[36,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "fluidium"
version = "${version}"
displayName = "Fluidium"
authors = "Kall"
description = '''
'''
#logoFile = ""